﻿version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: formneo-postgres
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "63306:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: formneo-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8082:80"
    depends_on:
      - postgres

  minio:
    image: minio/minio:latest
    container_name: formneo-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  backend:
    image: ghcr.io/muratmerdogan/formneo.server-backend:${TAG:-latest}
    container_name: formneo-backend
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__PostgreSqlConnection=Host=postgres;Port=5432;Database=${PG_DB};Username=${PG_USER};Password=${PG_PASSWORD};Timeout=120;
    ports:
      - "8080:8080"
    volumes:
      - dpkeys:/keys
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: formneo-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"  # Nginx 80 -> 127.0.0.1:5678 proxy yapacak
    environment:
      - GENERIC_TIMEZONE=Europe/Istanbul
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - N8N_PORT=5678
      - N8N_HOST=n8n.formneo.com
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.formneo.com/
      - N8N_EDITOR_BASE_URL=https://n8n.formneo.com/
      - N8N_SECURE_COOKIE=true
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  pgdata:

  dpkeys:
  minio_data:
  n8n_data: