using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace formneo.repository.Migrations
{
    /// <inheritdoc />
    public partial class tenant_lookup_fix : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Hatalı/yanlış adlandırılmış FK ve tabloları güvenli şekilde temizle
            migrationBuilder.Sql("ALTER TABLE \"Customers\" DROP CONSTRAINT IF EXISTS \"FK_Customers_LookupItems_CategoryId\";");
            migrationBuilder.Sql("ALTER TABLE \"Customers\" DROP CONSTRAINT IF EXISTS \"FK_Customers_LookupItems_CustomerTypeId\";");

            migrationBuilder.Sql("DROP TABLE IF EXISTS \"LookupItems\" CASCADE;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"LookupCategories\" CASCADE;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"LookupModules\" CASCADE;");

            // Varsa önceden oluşmuş TenantLookup tablolarını temizle (idempotent)
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"TenantLookupItems\" CASCADE;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"TenantLookupCategories\" CASCADE;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"TenantLookupModules\" CASCADE;");

            // TenantLookupModules
            migrationBuilder.Sql("CREATE TABLE \"TenantLookupModules\" (\"Id\" uuid PRIMARY KEY, \"MainClientId\" uuid NOT NULL, \"Key\" character varying(128) NOT NULL, \"Name\" character varying(256) NULL, \"IsTenantScoped\" boolean NOT NULL DEFAULT false, \"IsReadOnly\" boolean NOT NULL DEFAULT false, \"CreatedBy\" text NOT NULL, \"CreatedDate\" timestamp without time zone NOT NULL, \"UpdatedBy\" text NOT NULL, \"UpdatedDate\" timestamp without time zone NULL, \"IsDelete\" boolean NOT NULL DEFAULT false, \"UniqNumber\" integer GENERATED BY DEFAULT AS IDENTITY);");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_TenantLookupModules_MainClientId\" ON \"TenantLookupModules\"(\"MainClientId\");");
            migrationBuilder.Sql("ALTER TABLE \"TenantLookupModules\" ADD CONSTRAINT \"FK_TenantLookupModules_Clients_MainClientId\" FOREIGN KEY(\"MainClientId\") REFERENCES \"Clients\"(\"Id\");");

            // TenantLookupCategories
            migrationBuilder.Sql("CREATE TABLE \"TenantLookupCategories\" (\"Id\" uuid PRIMARY KEY, \"MainClientId\" uuid NOT NULL, \"ModuleId\" uuid NULL, \"Key\" character varying(128) NOT NULL, \"Description\" character varying(512) NULL, \"IsReadOnly\" boolean NOT NULL DEFAULT false, \"CreatedBy\" text NOT NULL, \"CreatedDate\" timestamp without time zone NOT NULL, \"UpdatedBy\" text NOT NULL, \"UpdatedDate\" timestamp without time zone NULL, \"IsDelete\" boolean NOT NULL DEFAULT false, \"UniqNumber\" integer GENERATED BY DEFAULT AS IDENTITY);");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_TenantLookupCategories_ModuleId\" ON \"TenantLookupCategories\"(\"ModuleId\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_TenantLookupCategories_MainClientId\" ON \"TenantLookupCategories\"(\"MainClientId\");");
            migrationBuilder.Sql("CREATE UNIQUE INDEX IF NOT EXISTS \"IX_TenantLookupCategories_MainClientId_ModuleId_Key\" ON \"TenantLookupCategories\"(\"MainClientId\",\"ModuleId\",\"Key\");");
            migrationBuilder.Sql("ALTER TABLE \"TenantLookupCategories\" ADD CONSTRAINT \"FK_TenantLookupCategories_Clients_MainClientId\" FOREIGN KEY(\"MainClientId\") REFERENCES \"Clients\"(\"Id\");");
            migrationBuilder.Sql("ALTER TABLE \"TenantLookupCategories\" ADD CONSTRAINT \"FK_TenantLookupCategories_TenantLookupModules_ModuleId\" FOREIGN KEY(\"ModuleId\") REFERENCES \"TenantLookupModules\"(\"Id\");");

            // TenantLookupItems
            migrationBuilder.Sql("CREATE TABLE \"TenantLookupItems\" (\"Id\" uuid PRIMARY KEY, \"MainClientId\" uuid NOT NULL, \"CategoryId\" uuid NOT NULL, \"Code\" character varying(64) NOT NULL, \"Name\" character varying(256) NOT NULL, \"NameLocalizedJson\" text NULL, \"OrderNo\" integer NOT NULL DEFAULT 0, \"IsActive\" boolean NOT NULL DEFAULT true, \"ExternalKey\" character varying(128) NULL, \"CreatedBy\" text NOT NULL, \"CreatedDate\" timestamp without time zone NOT NULL, \"UpdatedBy\" text NOT NULL, \"UpdatedDate\" timestamp without time zone NULL, \"IsDelete\" boolean NOT NULL DEFAULT false, \"UniqNumber\" integer GENERATED BY DEFAULT AS IDENTITY);");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_TenantLookupItems_CategoryId\" ON \"TenantLookupItems\"(\"CategoryId\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_TenantLookupItems_MainClientId\" ON \"TenantLookupItems\"(\"MainClientId\");");
            migrationBuilder.Sql("CREATE UNIQUE INDEX IF NOT EXISTS \"IX_TenantLookupItems_MainClientId_CategoryId_Code\" ON \"TenantLookupItems\"(\"MainClientId\",\"CategoryId\",\"Code\");");
            migrationBuilder.Sql("ALTER TABLE \"TenantLookupItems\" ADD CONSTRAINT \"FK_TenantLookupItems_Clients_MainClientId\" FOREIGN KEY(\"MainClientId\") REFERENCES \"Clients\"(\"Id\");");
            migrationBuilder.Sql("ALTER TABLE \"TenantLookupItems\" ADD CONSTRAINT \"FK_TenantLookupItems_TenantLookupCategories_CategoryId\" FOREIGN KEY(\"CategoryId\") REFERENCES \"TenantLookupCategories\"(\"Id\");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"TenantLookupItems\" CASCADE;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"TenantLookupCategories\" CASCADE;");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"TenantLookupModules\" CASCADE;");
        }
    }
}
