#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["formneo.api/formneo.api.csproj", "formneo.api/"]
COPY ["formneo.service/formneo.service.csproj", "formneo.service/"]
COPY ["formneo.repository/formneo.repository.csproj", "formneo.repository/"]
COPY ["formneo.core/formneo.core.csproj", "formneo.core/"]
COPY ["formneo.workflow/formneo.workflow.csproj", "formneo.workflow/"]
RUN dotnet restore "formneo.api/formneo.api.csproj"
COPY . .
WORKDIR "/src/formneo.api"
RUN dotnet build "formneo.api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "formneo.api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "formneo.api.dll"]